version: '3'
services:

  mysql:
    image: "mysql:8.0.23"
    volumes:
        - ./sql-data/db:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sisben1984"
      MYSQL_USER: "sisben"
      MYSQL_PASSWORD: "sisben1984"
      MYSQL_DATABASE: "oficina_sisben_db"
